version: "3.8"

services:
  namenode:
    build:
      context: .
      dockerfile: Dockerfile.namenode
    container_name: namenode
    ports:
      - "9870:9870"   # NameNode UI
      - "9000:9000"   # HDFS service
    environment:
      - CLUSTER_NAME=stock-hadoop
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - ./data:/data
    networks:
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    depends_on:
      - namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - ./data:/data
    networks:
      - hadoop

networks:
  hadoop:
